DISABLE:
  - CLOUDFORMATION
  - CSS
  - EDITORCONFIG
  - SPELL # Uncomment to disable checks of spelling mistakes

PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES|__init__.py|\.kubernetes/server/base)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/|\.eslintrc\.json)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
SHOW_ELAPSED_TIME: true
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false
PLUGINS:
  - https://raw.githubusercontent.com/oxsecurity/megalinter/main/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml

REPOSITORY_GITLEAKS_ARGUMENTS:
  - --no-git


SPELL_CSPELL_DISABLE_ERRORS: true
REPOSITORY_CHECKOV_DISABLE_ERRORS: true
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true
REPOSITORY_DUSTILOCK_DISABLE_ERRORS: true
REPOSITORY_GITLEAKS_DISABLE_ERRORS: true
REPOSITORY_SEMGREP_DISABLE_ERRORS: true
REPOSITORY_TRIVY_DISABLE_ERRORS: true
# disable npm-groovy-lint 
NPM_GROOVY_LINT_DISABLE_ERRORS: true
GROOVY_GROOVYLINT_DISABLE_ERRORS: true
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: true
YAML_YAMLLINT_DISABLE_ERRORS: true
XML_XMLLINT_DISABLE_ERRORS: true
MARKDOWN_MARKDOWN_TABLE_FORMATTER_DISABLE_ERRORS: true
YAML_V8R_DISABLE_ERRORS: true
