DISABLE:
  - CLOUDFORMATION
  - CSS
  - EDITORCONFIG
  - SPELL # Uncomment to disable checks of spelling mistakes

PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES|__init__.py|\.kubernetes/server/base)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/|\.eslintrc\.json)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
BASH_FILTER_REGEX_EXCLUDE: "(lib)"
SPELL_MISSPELL_FILTER_REGEX_EXCLUDE: '(\.automation/generated|docs/descriptors)'
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091"
PYTHON_FLAKE8_ARGUMENTS: --builtins="_"
SHOW_ELAPSED_TIME: true
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false
PLUGINS:
  - https://raw.githubusercontent.com/oxsecurity/megalinter/main/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml

HTML_HTMLHINT_DISABLE_ERRORS: true
SQL_SQLFLUFF_DISABLE_ERRORS: true
REPOSITORY_GITLEAKS_ARGUMENTS:
  - --no-git

PYTHON_PYLINT_DISABLE_ERRORS: true
PYTHON_BANDIT_DISABLE_ERRORS: true
PYTHON_BANDIT_FILTER_REGEX_EXCLUDE: .*test.*\.py
PYTHON_MYPY_ARGUMENTS: --cache-dir .mypy_cache

SPELL_CSPELL_DISABLE_ERRORS: true
REPOSITORY_CHECKOV_DISABLE_ERRORS: true
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true
REPOSITORY_DUSTILOCK_DISABLE_ERRORS: true
REPOSITORY_GITLEAKS_DISABLE_ERRORS: true
REPOSITORY_SEMGREP_DISABLE_ERRORS: true
REPOSITORY_TRIVY_DISABLE_ERRORS: true